#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
META_DIR="meta"
DOTBOT_DIR="${META_DIR}/dotbot"
PLUGINS_DIR="${META_DIR}/plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" \
	--plugin-dir "${PLUGINS_DIR}/dotbot-brew" \
	--plugin-dir "${PLUGINS_DIR}/dotbot-vscode" \
	"${@}"
